# Generated by Django 4.2 on 2023-05-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('dateCreation',)},
        ),
    ]
