# Generated by Django 4.2 on 2023-05-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
